### ISSUE TITLE
WebP example doesn't work on IE because WebPJS is too old

### ISSUE THREAD

**Issue by saschanaz** [xooyoozoo/yolo-octo-bugfixes#1]
WebPJS 0.0.2 does not use standard ArrayBuffer but use responseText hack to get raw binary data.

https://gist.github.com/SaschaNaz/bf6fe88a623c0fc896ef

This code is my fixed version which detects responseType property to check arraybuffer support.

**Comment by xooyoozoo** [comment]
Thanks for letting me know about IE issues.

I tried your fix on a local machine, but IE11 still wouldn't load WebP. Reverting to an old commit made WebP worked again, so the problem was (at least partly) in how I was using the decoder in a web worker.

I commented out some things in the new version to resolve console errors and tweaked function context, and it worked again. But closure-compiler optimized away your original fixes. ¯_(ツ)_/¯
